export interface AngieAction {
  id: string;
  type: 'navigate' | 'download_cv' | 'open_terminal' | 'contact_form';
  target?: string;
  labelKey: string;
}

export interface AngieKnowledgeEntry {
  id: string;
  category:
    | 'about'
    | 'stack'
    | 'case_study'
    | 'hiring'
    | 'contact'
    | 'cv'
    | 'certs'
    | 'pricing'
    | 'general';
  keywords: {
    en: string[];
    es: string[];
  };
  title: {
    en: string;
    es: string;
  };
  content: {
    en: string;
    es: string;
  };
  actions?: AngieAction[];
}

export const ANGIE_KNOWLEDGE_BASE: AngieKnowledgeEntry[] = [
  {
    id: 'bio_summary',
    category: 'about',
    keywords: {
      en: [
        'who is',
        'who is cesar',
        'about cesar',
        'bio',
        'profile',
        'summary',
        'background',
        'experience overview',
      ],
      es: [
        'quien es',
        'quien es cesar',
        'sobre cesar',
        'biografia',
        'perfil',
        'resumen',
        'trayectoria',
        'experiencia general',
      ],
    },
    title: {
      en: 'About César Gómez',
      es: 'Sobre César Gómez',
    },
    content: {
      en: 'César Gómez is a Senior Fullstack Engineer & Frontend Architect with 13+ years of experience building high-scale, production-grade applications. He specializes in Vue 3 / Nuxt 4 enterprise ecosystems, TypeScript contracts, reactive performance (60 FPS), and AI-Augmented Engineering with human oversight. Founding member at LingoQuesto and lead architect for multiple multi-tenant cloud platforms.',
      es: 'César Gómez es un Ingeniero Fullstack Senior y Arquitecto Frontend con más de 13 años de experiencia construyendo aplicaciones escalables en producción. Se especializa en ecosistemas empresariales Vue 3 / Nuxt 4, contratos TypeScript, rendimiento reactivo (60 FPS) e Ingeniería Aumentada por IA con control de calidad humano. Miembro fundador en LingoQuesto y arquitecto líder en plataformas cloud multi-inquilino.',
    },
    actions: [
      { id: 'act_about', type: 'navigate', target: '#about', labelKey: 'angie.actions.viewAbout' },
      {
        id: 'act_contact',
        type: 'contact_form',
        target: '#contact',
        labelKey: 'angie.actions.contactCesar',
      },
    ],
  },
  {
    id: 'vue_nuxt_mastery',
    category: 'stack',
    keywords: {
      en: [
        'vue',
        'vue 3',
        'nuxt',
        'nuxt 4',
        'vue developer',
        'vue architect',
        'composition api',
        'pinia',
        'nitro',
        'vue specialist',
        'vue mastery',
        'vue experience',
        'vue expertise',
      ],
      es: [
        'vue',
        'vue 3',
        'nuxt',
        'nuxt 4',
        'desarrollador vue',
        'arquitecto vue',
        'composition api',
        'pinia',
        'nitro',
        'especialista vue',
        'experiencia en vue',
        'experiencia en nuxt',
        'experiencia vue',
      ],
    },
    title: {
      en: 'Vue 3 & Nuxt 4 Architecture & Senior Mastery',
      es: 'Especialización y Liderazgo en Vue 3 / Nuxt 4',
    },
    content: {
      en: 'César is a Senior Vue 3 & Nuxt 4 Architect with 13+ years of production frontend engineering experience. His mastery covers end-to-end enterprise architectures: advanced Composition API, strict TypeScript contracts, Pinia state management, hybrid SSR/SSG rendering with Nitro Engine, microfrontend federation via Web Components, custom design systems (Tailwind CSS v4 / PrimeVue), and 60 FPS reactive performance with elite Core Web Vitals.',
      es: 'César es un especialista senior y arquitecto referente en Vue 3 y Nuxt 4 con más de 13 años de trayectoria en frontend. Su maestría abarca la arquitectura completa de aplicaciones web a escala empresarial: Composition API avanzada, contratos TypeScript estrictos, gestión de estado con Pinia, renderizado híbrido SSR/SSG con Nitro Engine, integración de microfrontends con Web Components, sistemas de diseño personalizados (Tailwind CSS v4 / PrimeVue) y optimización de rendimiento a 60 FPS con Core Web Vitals de nivel élite.',
    },
    actions: [
      {
        id: 'act_vue_profile',
        type: 'navigate',
        target: '/vue-frontend-developer',
        labelKey: 'angie.actions.viewTechStack',
      },
      {
        id: 'act_col_landing',
        type: 'navigate',
        target: '/vue-developer-colombia',
        labelKey: 'angie.actions.viewAbout',
      },
    ],
  },
  {
    id: 'tech_stack_core',
    category: 'stack',
    keywords: {
      en: [
        'stack',
        'technologies',
        'tools',
        'node',
        'tailwind',
        'framework',
        'vitest',
        'playwright',
        'tech stack',
      ],
      es: [
        'stack',
        'tecnologias',
        'herramientas',
        'node',
        'tailwind',
        'framework',
        'vitest',
        'playwright',
        'stack tecnico',
      ],
    },
    title: {
      en: 'Core Technical Stack',
      es: 'Stack Técnico Principal',
    },
    content: {
      en: "César's battle-tested stack includes:\n• Frontend: Vue 3 (Composition API), Nuxt 4 (SSG & SSR), TypeScript (Strict Mode), Vite, Nitro Engine.\n• UI & Styling: Tailwind CSS v4, PrimeVue 4, Motion-v, Custom Design Systems (Dark IDE Sanctuary).\n• State & Data: Pinia, VueUse, Web Workers, H3 Server Handlers, Reactive Streams.\n• Backend: Node.js, Express, Nitro Server Routes, REST APIs, JSON Schema Contracts.\n• Quality & Testing: Vitest, Playwright E2E, ESLint, Husky Pre-commit/Pre-push quality gates.",
      es: 'El stack de producción de César incluye:\n• Frontend: Vue 3 (Composition API), Nuxt 4 (SSG y SSR), TypeScript (Modo Estricto), Vite, Nitro Engine.\n• UI y Estilos: Tailwind CSS v4, PrimeVue 4, Motion-v, Design Systems a medida (Dark IDE Sanctuary).\n• Estado y Datos: Pinia, VueUse, Web Workers, Handlers de Servidor H3, Streams Reactivos.\n• Backend: Node.js, Express, Rutas de Servidor Nitro, APIs REST, Contratos JSON Schema.\n• Calidad y Pruebas: Vitest, Playwright E2E, ESLint, Husky Pre-commit/Pre-push quality gates.',
    },
    actions: [
      {
        id: 'act_stack',
        type: 'navigate',
        target: '#tech-stack',
        labelKey: 'angie.actions.viewTechStack',
      },
      { id: 'act_term', type: 'open_terminal', labelKey: 'angie.actions.runTelemetry' },
    ],
  },
  {
    id: 'case_colegium',
    category: 'case_study',
    keywords: {
      en: [
        'colegium',
        'colegium case study',
        'colegium cloud',
        'education',
        'edtech',
        'modules',
        'web components',
        'hackathon',
        'school platform',
      ],
      es: [
        'colegium',
        'caso colegium',
        'colegium cloud',
        'educacion',
        'edtech',
        'modulos',
        'web components',
        'hackathon',
        'plataforma educativa',
      ],
    },
    title: {
      en: 'Colegium Case Study',
      es: 'Caso de Estudio Colegium',
    },
    content: {
      en: 'At Colegium (a large-scale educational SaaS platform serving 100,000+ active students across Latin America), César worked as a Senior Frontend Developer:\n• Developed 12 next-generation educational modules, 3 internal tools for school administrators, and 3 shared libraries in Colegium Cloud.\n• Engineered Vue 3 Web Components and hybrid architectures that eliminated redundant code across teams.\n• Contributed to the enterprise Design System, standardizing navigation, forms, and data visualization patterns.\n• Awarded 4th place at the Colegium Hackathon 2024 with an AI chatbot for helpdesk ticketing and administrative automation.',
      es: 'En Colegium (plataforma SaaS educativa que atiende a más de 100.000 estudiantes en Latinoamérica), César se desempeñó como Desarrollador Frontend Senior:\n• Desarrolló 12 módulos educativos de próxima generación, 3 herramientas internas para administradores escolares y 3 bibliotecas compartidas en Colegium Cloud.\n• Implementó Web Components en Vue.js 3 y modelos híbridos que redujeron la duplicación de código entre equipos.\n• Contribuyó al ecosistema del Design System institucional, garantizando consistencia en navegación, formularios y visualización de datos.\n• Obtuvo el 4.º puesto en la Colegium Hackathon 2024 con un chatbot de IA para ticketing y automatización de helpdesk.',
    },
    actions: [
      {
        id: 'act_case_col',
        type: 'navigate',
        target: '/case-studies/colegium',
        labelKey: 'angie.actions.viewColegium',
      },
      {
        id: 'act_col_contact',
        type: 'contact_form',
        target: '#contact',
        labelKey: 'angie.actions.contactCesar',
      },
    ],
  },
  {
    id: 'case_lingoquesto',
    category: 'case_study',
    keywords: {
      en: [
        'lingoquesto',
        'lingo questo',
        'lingoquesto case study',
        'ai platform',
        'nlp',
        'conversational',
        'languages',
        'edtech',
      ],
      es: [
        'lingoquesto',
        'lingo questo',
        'caso lingoquesto',
        'plataforma lingoquesto',
        'plataforma ia',
        'nlp',
        'conversacional',
        'idiomas',
        'edtech',
      ],
    },
    title: {
      en: 'LingoQuesto Case Study',
      es: 'Caso de Estudio LingoQuesto',
    },
    content: {
      en: 'LingoQuesto is an AI-powered conversational language platform. As a founding engineer, César built the real-time dialogue simulation interface with WebSockets, audio streaming, LLM prompt pipelines, and responsive micro-interactions that boosted user retention by 65%.',
      es: 'LingoQuesto es una plataforma conversacional para el aprendizaje de idiomas impulsada por IA. Como ingeniero fundador, César construyó la interfaz de simulación de diálogo en tiempo real con WebSockets, streaming de audio, pipelines LLM y micro-interacciones que aumentaron la retención de usuarios en un 65%.',
    },
    actions: [
      {
        id: 'act_case_lq',
        type: 'navigate',
        target: '/case-studies/lingoquesto',
        labelKey: 'angie.actions.viewLingoQuesto',
      },
    ],
  },
  {
    id: 'case_tissini',
    category: 'case_study',
    keywords: {
      en: ['tissini', 'ecommerce', 'app', 'sales', 'cart', 'mobile'],
      es: ['tissini', 'comercio electronico', 'ecommerce', 'ventas', 'carrito', 'movil'],
    },
    title: {
      en: 'TISSINI Case Study',
      es: 'Caso de Estudio TISSINI',
    },
    content: {
      en: 'TISSINI empowers Hispanic micro-entrepreneurs. César optimized the digital catalog, checkout funnel, and mobile responsive experiences, drastically decreasing checkout latency and stabilizing Core Web Vitals across high-traffic sales events.',
      es: 'TISSINI impulsa a microempresarias hispanas. César optimizó el catálogo digital, el embudo de checkout y la experiencia móvil, reduciendo drásticamente la latencia en compras y estabilizando los Core Web Vitals durante eventos de alta demanda.',
    },
    actions: [
      {
        id: 'act_case_tis',
        type: 'navigate',
        target: '/case-studies/tissini',
        labelKey: 'angie.actions.viewTissini',
      },
    ],
  },
  {
    id: 'hiring_availability',
    category: 'hiring',
    keywords: {
      en: [
        'availability',
        'available',
        'current availability',
        'is he available',
        'start date',
        'hire',
        'hiring',
        'work with',
        'job offer',
        'modalities',
        'full time',
        'contract',
        'remote',
        'timezone',
        'rate',
        'services',
        'consulting',
      ],
      es: [
        'disponibilidad',
        'disponible',
        'disponibilidad actual',
        'esta disponible',
        'cuando puede empezar',
        'contratar',
        'contratacion',
        'trabajar',
        'oferta laboral',
        'modalidad',
        'tiempo completo',
        'full time',
        'part time',
        'remoto',
        'zona horaria',
        'tarifa',
        'consultoria',
        'servicios',
        'freelance',
      ],
    },
    title: {
      en: 'Availability & Engagement Options',
      es: 'Disponibilidad y Modalidades de Contratación',
    },
    content: {
      en: 'César is currently AVAILABLE for new senior engineering opportunities:\n• Modalities: Senior Contract, Frontend Architecture Consulting, or Full-Time Remote Engineering.\n• Focus: Vue 3 / Nuxt 4 Architecture, Core Web Vitals optimization, and AI-Augmented Engineering workflows.\n• Timezone: UTC-5 (EST / COT) with strong timezone overlap for US, LATAM, and European teams.\n• Languages: B1 English proficiency (intermediate technical communication & async documentation) and native Spanish.\n• How to coordinate: You can download his verified CV or head directly to the Contact section (#contact) to find his direct channels (Email: cesargomezh90@gmail.com, LinkedIn, WhatsApp) and submit a project briefing through the interactive form.',
      es: 'César está actualmente DISPONIBLE para asumir nuevos roles como Ingeniero Fullstack Senior o Arquitecto Frontend:\n• Modalidades: Contrato Senior, Consultoría en Arquitectura Frontend o Tiempo Completo Remoto (Full-Time).\n• Especialidad: Arquitectura Vue 3 / Nuxt 4, optimización de Core Web Vitals y flujos de Ingeniería Aumentada con IA.\n• Zona horaria: UTC-5 (EST / COT) con alta cobertura horaria para equipos en EE. UU., LATAM y Europa.\n• Idiomas: Nivel de inglés B1 (comunicación técnica fluida y colaboración asíncrona) y español nativo.\n• Para coordinar: Puedes descargar su CV actualizado o ir directamente a la sección de Contacto (#contact) para ver sus canales directos (Email: cesargomezh90@gmail.com, LinkedIn, WhatsApp) y enviar una propuesta mediante el formulario interactivo.',
    },
    actions: [
      {
        id: 'act_hire_contact',
        type: 'contact_form',
        target: '#contact',
        labelKey: 'angie.actions.discussProject',
      },
      { id: 'act_dl_cv', type: 'download_cv', labelKey: 'angie.actions.downloadCvNow' },
      {
        id: 'act_hire_profiles',
        type: 'navigate',
        target: '#hire-profiles',
        labelKey: 'angie.actions.viewProfiles',
      },
    ],
  },
  {
    id: 'languages_proficiency',
    category: 'about',
    keywords: {
      en: [
        'english',
        'english level',
        'language',
        'languages',
        'b1',
        'spanish',
        'bilingual',
        'speak english',
        'fluency',
        'communication',
      ],
      es: [
        'ingles',
        'nivel de ingles',
        'idioma',
        'idiomas',
        'b1',
        'espanol',
        'bilingue',
        'habla ingles',
        'fluidez',
        'comunicacion',
      ],
    },
    title: {
      en: 'Languages & English Level',
      es: 'Idiomas y Nivel de Inglés',
    },
    content: {
      en: "César's English proficiency is B1 (intermediate professional for technical discussions, reading and writing architecture specs, tickets, documentation, and agile async collaboration in distributed teams). His native language is Spanish. He is available for global remote distributed teams.",
      es: 'El nivel de inglés de César es B1 (intermedio profesional para comunicación técnica, lectura y redacción de especificaciones, tickets, documentación y colaboración ágil en equipos remotos distribuidos). Su idioma nativo es el español. Trabaja habitualmente con equipos remotos globales.',
    },
    actions: [
      { id: 'act_lang_cv', type: 'download_cv', labelKey: 'angie.actions.downloadCvNow' },
      {
        id: 'act_lang_contact',
        type: 'contact_form',
        target: '#contact',
        labelKey: 'angie.actions.contactCesar',
      },
    ],
  },
  {
    id: 'cv_download',
    category: 'cv',
    keywords: {
      en: ['cv', 'resume', 'curriculum', 'download cv', 'pdf', 'credentials'],
      es: ['cv', 'resume', 'curriculum', 'descargar cv', 'pdf', 'hoja de vida'],
    },
    title: {
      en: 'Download Résumé / CV',
      es: 'Descargar Hoja de Vida / CV',
    },
    content: {
      en: "You can download César's verified CV directly in English or Spanish summarizing his 13+ years of production experience, architecture achievements, and credentials. You can also visit the Contact section to connect via Email, LinkedIn, WhatsApp, or submit the contact form.",
      es: 'Puedes descargar el CV verificado de César directamente en inglés y español con el resumen de sus más de 13 años de experiencia en producción, arquitectura y credenciales. Además, puedes dirigirte a la sección de Contacto para comunicarte por Email, LinkedIn, WhatsApp o enviar un mensaje a través del formulario.',
    },
    actions: [
      { id: 'act_dl_cv', type: 'download_cv', labelKey: 'angie.actions.downloadCvNow' },
      {
        id: 'act_contact_form',
        type: 'contact_form',
        target: '#contact',
        labelKey: 'angie.actions.openContactForm',
      },
    ],
  },
  {
    id: 'certifications_info',
    category: 'certs',
    keywords: {
      en: ['certifications', 'licenses', 'credentials', 'linkedin learning', 'platzi', 'new relic'],
      es: [
        'certificaciones',
        'licencias',
        'credenciales',
        'linkedin learning',
        'platzi',
        'new relic',
      ],
    },
    title: {
      en: 'Certifications & Continuous Learning',
      es: 'Certificaciones y Aprendizaje Continuo',
    },
    content: {
      en: 'César holds 18+ verified credentials covering:\n• Advanced TypeScript (Enterprise Patterns, Scalable Monorepos, OOP).\n• AI Programming for JavaScript Developers & Custom GPT Architecture.\n• Observability Practitioner (New Relic Certified).\n• Data Structures in JavaScript (BSTs, Queues, Stacks).\n• Advanced Vue.js & Modern Build Tooling (Vite, Package Management).',
      es: 'César cuenta con más de 18 credenciales verificadas en:\n• TypeScript Avanzado (Patrones Empresariales, Monorepos Escalables, POO).\n• Programación con IA para Desarrolladores JS y Arquitectura GPT.\n• Observabilidad Práctica (Certificado por New Relic).\n• Estructuras de Datos en JavaScript (BSTs, Colas, Pilas).\n• Vue.js Avanzado y Herramientas de Compilación Modernas (Vite, NPM).',
    },
    actions: [
      {
        id: 'act_certs',
        type: 'navigate',
        target: '#certifications',
        labelKey: 'angie.actions.viewAllCerts',
      },
    ],
  },
  {
    id: 'contact_channels',
    category: 'contact',
    keywords: {
      en: [
        'contact',
        'how to contact',
        'contact channels',
        'contact details',
        'reach',
        'reach cesar',
        'coordinate',
        'email',
        'linkedin',
        'github',
        'whatsapp',
        'form',
        'talk',
        'schedule',
        'message',
        'phone',
      ],
      es: [
        'contacto',
        'contactar',
        'como contactar',
        'canales de contacto',
        'datos de contacto',
        'coordinar',
        'coordinacion',
        'email',
        'correo',
        'linkedin',
        'github',
        'whatsapp',
        'formulario',
        'hablar',
        'agendar',
        'mensaje',
        'escribir',
        'telefono',
      ],
    },
    title: {
      en: 'Contact & Coordination Channels',
      es: 'Canales de Contacto y Coordinación',
    },
    content: {
      en: 'To coordinate a project or discuss an engineering role with César, you have two direct options:\n1. Visit the Contact section (#contact) on this page: you will find his direct channels (Email: cesargomezh90@gmail.com, LinkedIn: linkedin.com/in/mrcego, WhatsApp: @mrcego.fsdev, GitHub: github.com/mrcego) along with the interactive briefing form.\n2. Download his verified Résumé / CV in English or Spanish to review his complete track record and credential history.',
      es: 'Para coordinar una oportunidad o conversar sobre un proyecto con César, tienes dos opciones directas:\n1. Ir a la sección de Contacto (#contact) en esta página: allí encontrarás sus canales directos (Email: cesargomezh90@gmail.com, LinkedIn: linkedin.com/in/mrcego, WhatsApp: @mrcego.fsdev, GitHub: github.com/mrcego) y el formulario interactivo de transmisión.\n2. Descargar su Hoja de Vida / CV verificado en inglés o español para revisar su historial completo de experiencia y certificaciones.',
    },
    actions: [
      {
        id: 'act_contact_form',
        type: 'contact_form',
        target: '#contact',
        labelKey: 'angie.actions.openContactForm',
      },
      { id: 'act_dl_cv', type: 'download_cv', labelKey: 'angie.actions.downloadCvNow' },
    ],
  },
  {
    id: 'companies_experience',
    category: 'case_study',
    keywords: {
      en: [
        'companies',
        'where did he work',
        'work history',
        'work experience',
        'previous jobs',
        'company',
        'career history',
        'employers',
        'experience',
        'clients',
      ],
      es: [
        'empresas',
        'donde ha trabajado',
        'donde trabajo',
        'historial laboral',
        'experiencia laboral',
        'trabajos anteriores',
        'companias',
        'empresas anteriores',
        'empleos',
        'carrera',
        'clientes',
      ],
    },
    title: {
      en: 'Work History & Enterprise Experience',
      es: 'Empresas y Trayectoria Laboral',
    },
    content: {
      en: 'Over his 13+ years in software engineering, César has delivered high-impact production architectures across major enterprise platforms:\n• Colegium (EdTech SaaS): Senior Frontend Developer architecting 12 educational modules, 3 admin tools, and 3 shared Vue 3 libraries for 100,000+ students.\n• LingoQuesto (AI Conversational Platform): Founding Fullstack Engineer building real-time WebSocket dialog simulations, audio streaming, and LLM pipelines (65% retention boost).\n• TISSINI (E-commerce): Optimized mobile sales funnels, checkout pipelines, and Core Web Vitals for Hispanic micro-entrepreneurs.\n• Multi-tenant Cloud & Independent Consulting: Designed scalable Vue/Nuxt frontends and Node.js microservices for diverse enterprise clients.',
      es: 'En sus más de 13 años de trayectoria, César ha liderado arquitecturas de alto impacto en producción para destacadas plataformas:\n• Colegium (SaaS EdTech): Desarrollador Frontend Senior construyendo 12 módulos educativos, 3 herramientas de administración y 3 librerías compartidas en Vue 3 para más de 100.000 estudiantes.\n• LingoQuesto (IA Conversacional): Ingeniero Fullstack Fundador desarrollando la simulación conversacional en tiempo real con WebSockets, streaming de audio y pipelines LLM (+65% retención).\n• TISSINI (Comercio Electrónico): Optimizó el embudo de ventas móvil y estabilizó Core Web Vitals en eventos masivos de compra.\n• Plataformas Cloud Multi-Inquilino y Consultoría: Arquitecturas frontend escalables en Vue/Nuxt y microservicios Node.js para clientes empresariales.',
    },
    actions: [
      { id: 'act_about', type: 'navigate', target: '#about', labelKey: 'angie.actions.viewAbout' },
      { id: 'act_dl_cv', type: 'download_cv', labelKey: 'angie.actions.downloadCvNow' },
    ],
  },
  {
    id: 'location_remote',
    category: 'about',
    keywords: {
      en: [
        'location',
        'where does he live',
        'country',
        'city',
        'colombia',
        'medellin',
        'remote',
        'timezone',
        'relocation',
        'where is he located',
        'where is cesar',
      ],
      es: [
        'ubicacion',
        'donde vive',
        'donde esta ubicado',
        'pais',
        'ciudad',
        'colombia',
        'medellin',
        'remoto',
        'zona horaria',
        'donde esta cesar',
        'residencia',
      ],
    },
    title: {
      en: 'Location & Remote Collaboration',
      es: 'Ubicación y Trabajo Remoto',
    },
    content: {
      en: 'César is based in Colombia (UTC-5 timezone / Eastern Standard Time equivalent) and works 100% remotely. He has extensive experience collaborating with distributed global teams across the United States, Latin America, and Europe with seamless daily overlap and async documentation practices.',
      es: 'César reside en Colombia (zona horaria UTC-5 / equivalente a EST) y trabaja 100% de forma remota. Cuenta con amplia experiencia colaborando con equipos distribuidos globales en Estados Unidos, Latinoamérica y Europa con cobertura horaria directa y comunicación técnica asíncrona.',
    },
    actions: [
      {
        id: 'act_contact_form',
        type: 'contact_form',
        target: '#contact',
        labelKey: 'angie.actions.openContactForm',
      },
    ],
  },
  {
    id: 'ai_augmented_engineering',
    category: 'about',
    keywords: {
      en: [
        'ai',
        'ai augmented',
        'artificial intelligence',
        'vibe coding',
        'llm',
        'webllm',
        'browserai',
        'prompts',
        'agents',
        'copilot',
        'ai workflow',
        'ai methodology',
      ],
      es: [
        'ia',
        'inteligencia artificial',
        'ingenieria aumentada',
        'vibe coding',
        'llm',
        'webllm',
        'browserai',
        'prompts',
        'agentes',
        'copilot',
        'flujo ia',
        'como usa ia',
      ],
    },
    title: {
      en: 'AI-Augmented Engineering Methodology',
      es: 'Metodología de Ingeniería Aumentada por IA',
    },
    content: {
      en: 'César applies AI-Augmented Engineering as an architectural leverage multiplier governed by strict human oversight and automated quality gates (TypeScript strict contracts, Vitest coverage, Playwright E2E, ESLint, and CI/CD). He integrates on-device LLMs (such as WebLLM/BrowserAI powering this portfolio concierge), agentic workflows, and semantic RAG systems into high-performance enterprise applications.',
      es: 'César aplica la Ingeniería Aumentada por IA como un multiplicador de productividad gobernado por estricta supervisión arquitectónica humana y compuertas de calidad automatizadas (TypeScript estricto, Vitest, Playwright E2E, ESLint y CI/CD). Integra modelos LLM locales en el navegador (como WebLLM/BrowserAI que da vida a este asistente), flujos agénticos y sistemas RAG semánticos en aplicaciones empresariales de alto rendimiento.',
    },
    actions: [
      {
        id: 'act_stack',
        type: 'navigate',
        target: '#tech-stack',
        labelKey: 'angie.actions.viewTechStack',
      },
      { id: 'act_term', type: 'open_terminal', labelKey: 'angie.actions.runTelemetry' },
    ],
  },
  {
    id: 'rates_pricing',
    category: 'pricing',
    keywords: {
      en: [
        'rate',
        'rates',
        'pricing',
        'how much',
        'cost',
        'salary',
        'budget',
        'fee',
        'compensation',
        'hourly rate',
        'monthly rate',
      ],
      es: [
        'tarifa',
        'tarifas',
        'precio',
        'cuanto cobra',
        'costo',
        'salario',
        'presupuesto',
        'honorarios',
        'compensacion',
        'tarifa por hora',
        'tarifa mensual',
      ],
    },
    title: {
      en: 'Rates & Compensation Structure',
      es: 'Tarifas y Estructura de Compensación',
    },
    content: {
      en: 'Engagement rates are tailored according to the modality and scope:\n• Senior Contract / Full-Time Remote: Competitive international senior contractor rates aligned with US/global markets.\n• Frontend Architecture Consulting & Audits: Structured per milestone, sprint, or retainer.\nTo discuss budget details and receive a customized technical proposal, reach out directly through the contact transmission form or via email (cesargomezh90@gmail.com).',
      es: 'Las tarifas se ajustan de acuerdo con la modalidad y el alcance del proyecto:\n• Contrato Senior / Full-Time Remoto: Tarifas competitivas de Senior Contractor alineadas con el mercado internacional.\n• Consultoría de Arquitectura Frontend y Auditorías: Esquemas por hito, sprint o retainer mensual.\nPara acordar detalles presupuestarios y recibir una propuesta personalizada, puedes escribir directamente a través del formulario de contacto o al correo cesargomezh90@gmail.com.',
    },
    actions: [
      {
        id: 'act_contact_form',
        type: 'contact_form',
        target: '#contact',
        labelKey: 'angie.actions.openContactForm',
      },
    ],
  },
  {
    id: 'angular_capability',
    category: 'stack',
    keywords: {
      en: [
        'angular',
        'angular developer',
        'angular 16',
        'rxjs',
        'signals',
        'standalone components',
        'angular migration',
        'migrate to vue',
        'legacy migration',
      ],
      es: [
        'angular',
        'desarrollador angular',
        'angular 16',
        'rxjs',
        'signals',
        'componentes independientes',
        'migracion angular',
        'migrar a vue',
        'migracion legacy',
      ],
    },
    title: {
      en: 'Angular Capability & Modernization',
      es: 'Capacidad Angular y Migraciones',
    },
    content: {
      en: 'César has extensive enterprise engineering experience in Angular up to v16+ (Standalone Components, Signals, RxJS reactive state, strictly typed Reactive Forms, and clean architecture). His dual mastery in Angular and Vue 3 / Nuxt 4 allows him to architect and lead pragmatic, zero-downtime migration and modernization paths for legacy enterprise applications.',
      es: 'César cuenta con amplia trayectoria en ingeniería frontend empresarial con Angular hasta la versión 16 (Componentes Standalone, Signals, gestión de estado reactivo con RxJS, Formularios Reactivos estrictamente tipados y arquitectura limpia). Su dominio dual en Angular y Vue 3 / Nuxt 4 le permite liderar rutas de migración y modernización pragmáticas para aplicaciones empresariales legadas.',
    },
    actions: [
      {
        id: 'act_stack',
        type: 'navigate',
        target: '#tech-stack',
        labelKey: 'angie.actions.viewTechStack',
      },
    ],
  },
  {
    id: 'web_development_services',
    category: 'hiring',
    keywords: {
      en: [
        'website',
        'web page',
        'build a website',
        'make a website',
        'create a website',
        'web development',
        'web app',
        'web application',
        'need a website',
        'frontend development',
        'landing page',
        'new project',
      ],
      es: [
        'pagina web',
        'hacer una pagina web',
        'crear pagina web',
        'crear una pagina web',
        'necesito una pagina web',
        'necesito hacer una pagina web',
        'desarrollo web',
        'sitio web',
        'crear sitio web',
        'aplicacion web',
        'crear una web',
        'necesito una web',
        'construir pagina',
        'diseno web',
        'desarrollo frontend',
        'programar pagina',
        'nuevo proyecto',
      ],
    },
    title: {
      en: 'Web Development & Web Applications',
      es: 'Desarrollo de Páginas y Aplicaciones Web',
    },
    content: {
      en: 'César Gómez specializes in engineering modern, ultra-fast, custom websites and web applications using Vue 3, Nuxt 4, TypeScript, and Tailwind CSS:\n• High-Performance Websites & Landing Pages: Sub-second load times, 100/100 Core Web Vitals, and technical SEO.\n• Web Applications & SaaS Platforms: Scalable frontend architecture, robust state management, and seamless API integration.\n• Modernization & Redesign: Migration of legacy platforms to modern standards with responsive, accessible UI.\nYou can submit your project briefing via the contact form (#contact) or reach out via Email/WhatsApp to coordinate a technical proposal.',
      es: 'César Gómez diseña y construye páginas y aplicaciones web modernas, ultrarrápidas y a la medida utilizando Vue 3, Nuxt 4, TypeScript y Tailwind CSS:\n• Sitios Web y Landing Pages de Alto Rendimiento: Carga instantánea (sub-segundo), 100/100 en Core Web Vitals y SEO técnico optimizado.\n• Aplicaciones Web y Plataformas SaaS: Arquitecturas frontend escalables, gestión de estado robusta y conexión fluida con APIs REST.\n• Modernización y Rediseño: Migración de sistemas legados hacia estándares modernos con diseño responsive y accesible.\nPuedes enviar un resumen de tu proyecto a través del formulario de contacto (#contact) o escribirle directamente por Email o WhatsApp para coordinar una propuesta técnica.',
    },
    actions: [
      {
        id: 'act_web_contact',
        type: 'contact_form',
        target: '#contact',
        labelKey: 'angie.actions.openContactForm',
      },
      {
        id: 'act_web_profiles',
        type: 'navigate',
        target: '#hire-profiles',
        labelKey: 'angie.actions.viewProfiles',
      },
      {
        id: 'act_web_stack',
        type: 'navigate',
        target: '#tech-stack',
        labelKey: 'angie.actions.viewTechStack',
      },
    ],
  },
  {
    id: 'website_pricing_scope',
    category: 'pricing',
    keywords: {
      en: [
        'how much for a website',
        'website cost',
        'website price',
        'cost of a website',
        'website pricing',
        'how much does cesar charge',
        'landing page cost',
        'web app quote',
        'project budget',
        'estimate website',
      ],
      es: [
        'cuanto cobra por una pagina web',
        'cuanto cobra cesar por una pagina web',
        'cuanto cuesta una pagina web',
        'cuanto vale una pagina web',
        'precio de una pagina web',
        'costo de una pagina web',
        'cotizacion de pagina web',
        'presupuesto pagina web',
        'cuanto cobra por un sitio web',
        'costo de landing page',
        'cuanto cuesta un desarrollo',
        'precio de desarrollo web',
      ],
    },
    title: {
      en: 'Website & Web Application Pricing',
      es: 'Precios y Cotización de Sitios y Aplicaciones Web',
    },
    content: {
      en: 'The investment for a web project with César depends on scope and technical requirements:\n• High-Impact Landing Page / Corporate Website: Custom design, sub-second load times, 100/100 Core Web Vitals, and technical SEO. Quoted on a fixed-scope milestone model.\n• Fullstack Web App / SaaS MVP / E-commerce: Custom frontend, TypeScript API integration, responsive dashboards, and cloud deployment. Quoted by sprint or milestone.\n• Senior Retainer / Monthly Dedicated: For ongoing roadmap execution and feature evolution.\nTo receive a formal, transparent estimate tailored to your project in under 24h, submit a brief in the Contact section (#contact) or message César directly via WhatsApp or Email.',
      es: 'La inversión para un proyecto web con César se adapta a la complejidad y alcance técnico requerido:\n• Landing Page / Sitio Corporativo de Alto Impacto: Diseño a medida, carga en menos de 1 segundo, 100/100 en Core Web Vitals y SEO técnico optimizado. Se cotiza bajo presupuesto cerrado por hitos de entrega.\n• Aplicación Web / SaaS MVP / E-commerce: Frontend interactivo, integración de APIs TypeScript, panel administrativo y despliegue cloud. Se estructura por sprints o entregables.\n• Retainer Mensual / Dedicación Continua: Para acompañamiento evolutivo y desarrollo de nuevas funcionalidades.\nPara recibir una cotización detallada y formal en menos de 24 horas, puedes enviar los requerimientos mediante el formulario de Contacto (#contact) o escribirle directamente por WhatsApp o Email.',
    },
    actions: [
      {
        id: 'act_pricing_contact',
        type: 'contact_form',
        target: '#contact',
        labelKey: 'angie.actions.openContactForm',
      },
      {
        id: 'act_pricing_hire',
        type: 'navigate',
        target: '#hire-profiles',
        labelKey: 'angie.actions.viewProfiles',
      },
    ],
  },
  {
    id: 'engineering_leadership_quality',
    category: 'stack',
    keywords: {
      en: [
        'what did cesar lead',
        'what has cesar led',
        'what projects did he lead',
        'projects led by cesar',
        'leadership experience',
        'technical leadership',
        'engineering leadership',
        'teams led by cesar',
        'leadership track record',
        'lead frontend',
        'code quality',
        'code review',
        'software architecture',
        'testing strategy',
        'vitest',
        'playwright',
        'design patterns',
        'solid',
        'clean code',
        'tech lead',
        'engineering manager',
        'mentorship',
      ],
      es: [
        'que lidero cesar',
        'que lidero',
        'que ha liderado',
        'que proyectos lidero',
        'liderazgo de cesar',
        'proyectos liderados',
        'iniciativas lideradas',
        'experiencia como lider',
        'liderazgo tecnico',
        'lider de equipo',
        'lider frontend',
        'trayectoria de liderazgo',
        'que equipos lidero',
        'calidad de codigo',
        'code review',
        'arquitectura de software',
        'estrategia de testing',
        'pruebas unitarias',
        'vitest',
        'playwright',
        'patrones de diseno',
        'solid',
        'clean code',
        'tech lead',
        'mentoria',
        'buenas practicas',
      ],
    },
    title: {
      en: 'Technical Leadership & Project Track Record',
      es: 'Liderazgo Técnico y Proyectos Liderados',
    },
    content: {
      en: 'Throughout his 13+ years in engineering, César has led major technical initiatives and high-scale architectures:\n• Colegium (EdTech SaaS): Led the engineering of 12 next-gen modules, 3 school admin tools, and 3 shared Vue 3 libraries for 100k+ students, standardizing the institutional Design System.\n• LingoQuesto (AI Conversational Platform): As Founding Engineer, led the real-time WebSocket dialog architecture, audio streaming, and prompt pipelines (65% user retention boost).\n• TISSINI (E-commerce): Led the checkout funnel and mobile UX optimization, eliminating transaction bottlenecks under heavy traffic.\n• Engineering Culture: Establishes automated CI/CD quality gates (strict TypeScript, 100% Vitest/Playwright coverage), architectural RFCs, and team mentorship.',
      es: 'A lo largo de sus más de 13 años de trayectoria, César ha liderado iniciativas técnicas y arquitecturas de alto impacto:\n• Colegium (SaaS EdTech): Lideró el desarrollo de 12 módulos educativos, 3 herramientas de administración y 3 librerías compartidas en Vue 3 para más de 100.000 estudiantes, estandarizando el Design System institucional.\n• LingoQuesto (IA Conversacional): Como Ingeniero Fundador, lideró la arquitectura de diálogo en tiempo real con WebSockets, streaming de audio y pipelines de prompts (+65% de retención).\n• TISSINI (Comercio Electrónico): Lideró la optimización integral del embudo de ventas y estabilidad de Core Web Vitals en eventos de alta demanda.\n• Cultura de Ingeniería: Implementa compuertas de calidad CI/CD (TypeScript estricto, Vitest, Playwright E2E), especificaciones RFC y mentoría técnica a desarrolladores.',
    },
    actions: [
      {
        id: 'act_lead_stack',
        type: 'navigate',
        target: '#tech-stack',
        labelKey: 'angie.actions.viewTechStack',
      },
      {
        id: 'act_lead_contact',
        type: 'contact_form',
        target: '#contact',
        labelKey: 'angie.actions.contactCesar',
      },
    ],
  },
  {
    id: 'recruiter_b2b_compliance',
    category: 'hiring',
    keywords: {
      en: [
        'recruiter',
        'headhunter',
        'b2b contract',
        'w8ben',
        'contractor',
        'years of experience',
        'seniority',
        'onboarding',
        'immediate availability',
        'talent partner',
        'payroll',
        'deel',
        'remote com',
      ],
      es: [
        'recruiter',
        'recruiters',
        'headhunter',
        'contrato b2b',
        'contratacion b2b',
        'contratacion b2b internacional',
        'contratacion internacional',
        'informacion para recruiters',
        'w8ben',
        'contratista',
        'anios de experiencia',
        'seniority',
        'incorporacion',
        'disponibilidad inmediata',
        'proceso de seleccion',
        'facturacion internacional',
        'deel',
        'remote',
      ],
    },
    title: {
      en: 'Recruitment, Seniority & International B2B Compliance',
      es: 'Información para Recruiters, Seniority y Contratación B2B',
    },
    content: {
      en: 'Key facts for Technical Recruiters and Talent Acquisition Partners:\n• Seniority: 13+ years of continuous production software engineering experience (IC Senior & Frontend Lead).\n• Contract Readiness: Available for direct international B2B / Senior Contractor agreements (W-8BEN compliant, invoiceable via Deel, Remote.com, Wise, or direct wire).\n• Timezone & Onboarding: Located in Colombia (UTC-5 / EST equivalent), offering full timezone alignment with US, LATAM, and European teams with immediate onboarding capability.\n• Verified Track Record: Production experience across EdTech (Colegium, 100k+ users), AI Platforms (LingoQuesto), and E-commerce (TISSINI). Download his verified CV or book a briefing via the contact section.',
      es: 'Información clave para Recruiters Técnicos y Partners de Talento:\n• Seniority: Más de 13 años de trayectoria continua en desarrollo de software en producción (Senior IC y Frontend Lead).\n• Modalidad Contractual: Listo para contratos internacionales B2B / Senior Contractor (cumplimiento W-8BEN, facturación mediante Deel, Remote.com, Wise o transferencia bancaria directa).\n• Zona Horaria e Incorporación: Ubicado en Colombia (UTC-5 / equivalente a EST), con cobertura horaria completa para equipos en EE. UU., LATAM y Europa, y disponibilidad de incorporación inmediata.\n• Trayectoria Comprobada: Experiencia en EdTech (Colegium, 100k+ usuarios), Plataformas IA (LingoQuesto) y E-commerce (TISSINI). Puedes descargar su CV verificado o contactarlo directamente en la sección de contacto.',
    },
    actions: [
      {
        id: 'act_rec_cv',
        type: 'download_cv',
        labelKey: 'angie.actions.downloadCvNow',
      },
      {
        id: 'act_rec_contact',
        type: 'contact_form',
        target: '#contact',
        labelKey: 'angie.actions.discussProject',
      },
    ],
  },
  {
    id: 'founder_mvp_startup',
    category: 'hiring',
    keywords: {
      en: [
        'founder',
        'startup',
        'mvp',
        'build mvp',
        'launch startup',
        'founding engineer',
        'cost reduction',
        'zero to one',
        'rapid prototyping',
        'startup cto',
        'seed stage',
      ],
      es: [
        'founder',
        'startup',
        'mvp',
        'construir mvp',
        'crear mvp',
        'lanzar startup',
        'ingeniero fundador',
        'founding engineer',
        'reducir costos cloud',
        'de cero a uno',
        'prototipo rapido',
        'cto startup',
      ],
    },
    title: {
      en: 'Startup Engineering & 0-to-1 MVP Delivery',
      es: 'Ingeniería para Startups y Desarrollo de MVP (0 a 1)',
    },
    content: {
      en: 'For Startup Founders, CTOs, and Early-Stage Teams:\n• 0-to-1 Speed: As a Founding Engineer at LingoQuesto, César took products from whiteboard concept to live production in weeks, establishing architecture that scaled with 65% user retention.\n• Cloud Cost Efficiency: Leverages Static Generation (SSG), Edge Functions, and Serverless architectures to deliver sub-second performance while slashing infrastructure bills by up to 80%.\n• Product Ownership: Bridges business objectives and technical execution, prioritizing features that validate product-market fit and drive user acquisition without accumulating architectural debt.',
      es: 'Para Founders de Startups, CTOs y Equipos en Etapa Temprana (Seed/Early):\n• Velocidad de 0 a 1: Como Ingeniero Fundador en LingoQuesto, César llevó el producto desde el concepto inicial hasta producción en pocas semanas, creando una base técnica que escaló con un 65% de retención.\n• Eficiencia de Costos Cloud: Utiliza generación estática (SSG), Edge Functions y arquitecturas Serverless para lograr tiempos de carga instantáneos reduciendo hasta un 80% los costos fijos de servidores.\n• Enfoque de Producto: Conecta la visión de negocio con la ejecución técnica, priorizando las funcionalidades que validan el Product-Market Fit sin generar deuda técnica.',
    },
    actions: [
      {
        id: 'act_founder_lq',
        type: 'navigate',
        target: '/case-studies/lingoquesto',
        labelKey: 'angie.actions.viewLingoQuesto',
      },
      {
        id: 'act_founder_contact',
        type: 'contact_form',
        target: '#contact',
        labelKey: 'angie.actions.discussProject',
      },
    ],
  },
  {
    id: 'frontend_performance_seo',
    category: 'stack',
    keywords: {
      en: [
        'performance',
        'core web vitals',
        'lighthouse',
        'speed',
        'sub second',
        'page speed',
        'seo optimization',
        'google ranking',
        'fast website',
        'cls',
        'lcp',
        'fid',
        'inp',
      ],
      es: [
        'rendimiento',
        'velocidad',
        'core web vitals',
        'lighthouse',
        'optimizacion web',
        'seo tecnico',
        'posicionamiento google',
        'velocidad de carga',
        'pagina rapida',
        'cls',
        'lcp',
        'inp',
        'tbt',
      ],
    },
    title: {
      en: 'Core Web Vitals, Performance & Technical SEO',
      es: 'Rendimiento Extremo, Core Web Vitals y SEO Técnico',
    },
    content: {
      en: 'César engineers web frontends for elite performance and search discoverability:\n• Core Web Vitals: 100/100 Lighthouse scores, sub-second TTFB, 0 Cumulative Layout Shift (CLS: 0.000), and sub-50ms Interaction to Next Paint (INP).\n• Technical SEO: Rich JSON-LD Schema.org graphs (Person, ProfilePage, FAQPage, ItemList), Microformats2 (h-card) semantic markup, GEO AI engine optimization, and automated localized sitemaps.\n• Performance Architecture: Inlined critical CSS, lazy asset decoding, offline icon bundling, and Web Worker thread offloading for silky-smooth 60 FPS interactions.',
      es: 'César construye interfaces web optimizadas para máxima velocidad y posicionamiento en buscadores:\n• Core Web Vitals: Puntajes de 100/100 en Lighthouse, TTFB sub-segundo, 0 desvíos de diseño (CLS: 0.000) e interactividad instantánea (INP < 50ms).\n• SEO Técnico y GEO: Marcado estructurado Schema.org JSON-LD (Person, FAQPage, ProfilePage, ItemList), Microformats2 semántico (h-card), optimización para motores de IA (GEO) y sitemaps automáticos con paridad de idiomas.\n• Arquitectura de Rendimiento: CSS crítico inyectado, decodificación diferida de recursos, bundle de iconos offline y ejecución en Web Workers para mantener 60 FPS constantes.',
    },
    actions: [
      {
        id: 'act_perf_terminal',
        type: 'open_terminal',
        labelKey: 'angie.actions.runTelemetry',
      },
      {
        id: 'act_perf_contact',
        type: 'contact_form',
        target: '#contact',
        labelKey: 'angie.actions.openContactForm',
      },
    ],
  },
];
