/**
 * Shared CSP + Netlify `_headers` builders.
 * Security headers ship in `_headers` because GH Actions deploys only
 * `.output/public` (`netlify deploy --no-build --dir=...`) — `netlify.toml`
 * [[headers]] are not present in that publish tree.
 *
 * Keep script-src permissive enough for Nuxt SSG inline payloads — see write-csp-headers.mjs.
 */

/** @returns {string[]} */
export function buildCspDirectives() {
  return [
    "default-src 'self'",
    "base-uri 'self'",
    "object-src 'none'",
    "frame-ancestors 'none'",
    "form-action 'self'",
    "img-src 'self' data:",
    "font-src 'self'",
    "style-src 'self' 'unsafe-inline'",
    // Nuxt SSG inlines window.__NUXT__ per HTML; hashes/TT break Vue boot on this stack.
    "script-src 'self' 'unsafe-inline'",
    "connect-src 'self'",
    "manifest-src 'self'",
    'upgrade-insecure-requests',
  ];
}

/** @returns {string} */
export function buildCspHeaderValue() {
  return buildCspDirectives().join('; ');
}

/**
 * Static security headers applied to every path via Netlify `_headers`.
 * @returns {Record<string, string>}
 */
export function buildSecurityHeaders() {
  return {
    'X-Frame-Options': 'DENY',
    'X-Content-Type-Options': 'nosniff',
    'Referrer-Policy': 'strict-origin-when-cross-origin',
    'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), interest-cohort=()',
    'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload',
    'Cross-Origin-Opener-Policy': 'same-origin',
    'Cross-Origin-Resource-Policy': 'same-origin',
  };
}

/**
 * @param {string} csp
 * @param {Record<string, string>} [security]
 */
export function buildNetlifyHeadersFile(
  csp = buildCspHeaderValue(),
  security = buildSecurityHeaders(),
) {
  const securityLines = Object.entries(security)
    .map(([name, value]) => `  ${name}: ${value}`)
    .join('\n');

  return `\
#
# Generated by scripts/write-csp-headers.mjs — do not edit by hand.
# Deployed via artifact + netlify deploy --no-build — headers must live here.
#
/*
  Content-Security-Policy: ${csp}
${securityLines}
`;
}

/**
 * Parse the first Content-Security-Policy value from a Netlify `_headers` file.
 * @param {string} headersText
 * @returns {string | null}
 */
export function parseCspFromHeadersFile(headersText) {
  const match = headersText.match(/Content-Security-Policy:\s*(.+)/i);
  return match?.[1]?.trim() ?? null;
}

/**
 * @param {string} headersText
 * @param {string} headerName
 * @returns {string | null}
 */
export function parseHeaderFromHeadersFile(headersText, headerName) {
  const escaped = headerName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const match = headersText.match(new RegExp(`^\\s*${escaped}:\\s*(.+)$`, 'im'));
  return match?.[1]?.trim() ?? null;
}
