/**
 * Shared CSP builders for Netlify `_headers` and unit tests.
 * Keep script-src permissive enough for Nuxt SSG inline payloads — see write-csp-headers.mjs.
 */

/** @returns {string[]} */
export function buildCspDirectives() {
  return [
    "default-src 'self'",
    "base-uri 'self'",
    "object-src 'none'",
    "frame-ancestors 'none'",
    "form-action 'self'",
    "img-src 'self' data:",
    "font-src 'self'",
    "style-src 'self' 'unsafe-inline'",
    "script-src 'self' 'unsafe-inline'",
    "connect-src 'self'",
    "manifest-src 'self'",
    'upgrade-insecure-requests',
  ];
}

/** @returns {string} */
export function buildCspHeaderValue() {
  return buildCspDirectives().join('; ');
}

/** @param {string} csp */
export function buildNetlifyHeadersFile(csp = buildCspHeaderValue()) {
  return `\
#
# Generated by scripts/write-csp-headers.mjs — do not edit by hand.
#
/*
  Content-Security-Policy: ${csp}
`;
}

/**
 * Parse the first Content-Security-Policy value from a Netlify `_headers` file.
 * @param {string} headersText
 * @returns {string | null}
 */
export function parseCspFromHeadersFile(headersText) {
  const match = headersText.match(/Content-Security-Policy:\s*(.+)/i);
  return match?.[1]?.trim() ?? null;
}
