/**
 * Shared CSP + Netlify `_headers` builders.
 * Security headers ship in `_headers` because GH Actions deploys only
 * `.output/public` (`netlify deploy --no-build --dir=...`) — `netlify.toml`
 * [[headers]] are not present in that publish tree.
 *
 * After generate, write-csp-headers.mjs hashes executable inline `<script>` bodies
 * so we can drop script-src 'unsafe-inline' while keeping Nuxt SSG payloads.
 */

import { createHash } from 'node:crypto';
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';

/**
 * @param {string} dir
 * @returns {Generator<string>}
 */
function* walkHtmlFiles(dir) {
  if (!existsSync(dir)) return;
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    let st;
    try {
      st = statSync(full);
    } catch {
      continue;
    }
    if (st.isDirectory()) {
      yield* walkHtmlFiles(full);
    } else if (name.endsWith('.html')) {
      yield full;
    }
  }
}

/**
 * Executable inline scripts only (skip JSON / importmap payloads).
 * @param {string} html
 * @returns {string[]}
 */
export function extractExecutableInlineScripts(html) {
  const bodies = [];
  const re = /<script\b([^>]*)>([\s\S]*?)<\/script>/gi;
  let match;
  while ((match = re.exec(html)) !== null) {
    const attrs = match[1] || '';
    const body = match[2] ?? '';
    if (/\bsrc\s*=/i.test(attrs)) continue;
    if (!body.trim()) continue;
    const typeMatch = attrs.match(/\btype\s*=\s*["']([^"']+)["']/i);
    const type = typeMatch?.[1]?.trim().toLowerCase() ?? 'text/javascript';
    if (
      type === 'application/json' ||
      type === 'importmap' ||
      type === 'application/ld+json' ||
      type.endsWith('+json')
    ) {
      continue;
    }
    bodies.push(body);
  }
  return bodies;
}

/** @param {string} content */
export function hashInlineScript(content) {
  const digest = createHash('sha256').update(content, 'utf8').digest('base64');
  return `'sha256-${digest}'`;
}

/**
 * @param {string} publicDir
 * @returns {string[]} sorted unique CSP hash tokens
 */
export function collectInlineScriptHashes(publicDir) {
  const hashes = new Set();
  for (const file of walkHtmlFiles(publicDir)) {
    const html = readFileSync(file, 'utf8');
    for (const body of extractExecutableInlineScripts(html)) {
      hashes.add(hashInlineScript(body));
    }
  }
  return [...hashes].sort();
}

/**
 * @param {{ scriptHashes?: string[], enableTrustedTypes?: boolean }} [options]
 * @returns {string[]}
 */
export function buildCspDirectives(options = {}) {
  const scriptHashes = options.scriptHashes ?? [];
  const enableTrustedTypes = options.enableTrustedTypes ?? false;

  const scriptSrc =
    scriptHashes.length > 0
      ? ['script-src', "'self'", ...scriptHashes].join(' ')
      : "script-src 'self' 'unsafe-inline'";

  /** @type {string[]} */
  const directives = [
    "default-src 'self'",
    "base-uri 'self'",
    "object-src 'none'",
    "frame-ancestors 'none'",
    "form-action 'self'",
    "img-src 'self' data:",
    "font-src 'self'",
    "style-src 'self' 'unsafe-inline'",
    scriptSrc,
    "connect-src 'self'",
    "manifest-src 'self'",
    'upgrade-insecure-requests',
  ];

  if (enableTrustedTypes) {
    // Vue 3 registers a Trusted Types policy named `vue`.
    directives.push("require-trusted-types-for 'script'");
    directives.push('trusted-types vue default');
  }

  return directives;
}

/**
 * @param {{ scriptHashes?: string[], enableTrustedTypes?: boolean }} [options]
 * @returns {string}
 */
export function buildCspHeaderValue(options = {}) {
  return buildCspDirectives(options).join('; ');
}

/**
 * Static security headers applied to every path via Netlify `_headers`.
 * @returns {Record<string, string>}
 */
export function buildSecurityHeaders() {
  return {
    'X-Frame-Options': 'DENY',
    'X-Content-Type-Options': 'nosniff',
    'Referrer-Policy': 'strict-origin-when-cross-origin',
    'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), interest-cohort=()',
    'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload',
    'Cross-Origin-Opener-Policy': 'same-origin',
    'Cross-Origin-Resource-Policy': 'same-origin',
  };
}

/**
 * @param {string} csp
 * @param {Record<string, string>} [security]
 */
export function buildNetlifyHeadersFile(
  csp = buildCspHeaderValue(),
  security = buildSecurityHeaders(),
) {
  const securityLines = Object.entries(security)
    .map(([name, value]) => `  ${name}: ${value}`)
    .join('\n');

  return `\
#
# Generated by scripts/write-csp-headers.mjs — do not edit by hand.
# Deployed via artifact + netlify deploy --no-build — headers must live here.
#
/*
  Content-Security-Policy: ${csp}
${securityLines}
`;
}

/**
 * Parse the first Content-Security-Policy value from a Netlify `_headers` file.
 * @param {string} headersText
 * @returns {string | null}
 */
export function parseCspFromHeadersFile(headersText) {
  const match = headersText.match(/Content-Security-Policy:\s*(.+)/i);
  return match?.[1]?.trim() ?? null;
}

/**
 * @param {string} headersText
 * @param {string} headerName
 * @returns {string | null}
 */
export function parseHeaderFromHeadersFile(headersText, headerName) {
  const escaped = headerName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const match = headersText.match(new RegExp(`^\\s*${escaped}:\\s*(.+)$`, 'im'));
  return match?.[1]?.trim() ?? null;
}
