import { useExpertiseLandingSeo } from './useExpertiseLandingSeo';

export const useVueDeveloperLandingSeo = () =>
  useExpertiseLandingSeo({
    translationKey: 'landingVue',
    paths: {
      en: '/vue-frontend-developer',
      es: '/desarrollador-vue',
    },
    jobTitles: [
      'Desarrollador Vue.js',
      'Desarrollador Vue',
      'Vue.js Developer',
      'Vue Developer',
      'Senior Vue Frontend Developer',
      'Desarrollador Nuxt.js',
      'Nuxt.js Developer',
    ],
    knowsAbout: [
      'Vue.js',
      'Vue 3',
      'Desarrollador Vue',
      'Desarrollador Vue.js',
      'Nuxt.js',
      'Nuxt 4',
      'TypeScript',
      'Pinia',
      'Vue Router',
      'Vite',
      'Composition API',
      'PrimeVue',
      'Tailwind CSS',
      'Frontend Development',
      'Senior Frontend Development',
      'Website Development',
      'Design Systems',
      'Micro-frontends',
      'SSR/SSG',
      'Core Web Vitals',
      'Accessibility',
      'Web Performance',
      'Ed-tech',
      'Remote Vue Contracting',
    ],
  });
